FROM continuumio/miniconda3:latest

ENV version="0.9.1"
ENV version_suffix=""

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps libblosc1 wget openjdk-11-jre unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN conda install -c ome bioformats2raw==${version}${version_suffix} -y 
